### ISSUE TITLE
Extract framework into separate repo/npm module

### ISSUE THREAD

**Issue by watsonarw** [twlevelup/watch_edition#10]
### Overview

**Note: Long term, many things are needed before this is possible**

In order to separate the framework from the student's apps, it would be nice to extract the watch framework code into an NPM module that the student app can require and not have to worry about. This would allow us to have more control over how much the watch can do (limited scope gives them other issues to solve), as well as simplifying the app from the students' perspective, and make the app seem less daunting, particularly for those who don't have much javascript experience.

**Comment by emirose** [comment]
I've started working on this. You can see the work in progress here:
- https://github.com/twlevelup/watch_framework
- https://github.com/emirose/watch_edition

After looking at how express handles exports, I think that approach is better. I'll refactor the framework to do that(eg: var watchFramework = require('watch_framework'); 
                   var watchFace = watchFramework.WatchFace();

Let me know if you have other thoughts/notes. Thanks!
