### ISSUE TITLE
Convert from MVC to Components based structure

### ISSUE THREAD

**Issue by raytung** [twlevelup/watch_edition#26]
On top of all the benefits that come it,  component-based structure can also better position ourselves if / when we want to move into modern SPA

**Comment by watsonarw** [comment]
I have a few thoughts on this.

* I agree that a component-based structure is a more modern approach to building a SPA. However, LevelUp is not necessarily about how to build a SPA.
* I feel like a react/redux app would probably be easier for the students to get their heads around sooner, when compared to the current app. I also think that testing a react/redux would be easier, and help encourage TDD.
* My suspicion would be that changing this to a component-based structure would likely be easier with a full re-write.

**Comment by raytung** [comment]
@watsonarw yeah I agree

**Comment by raytung** [comment]
@watsonarw yeah I agree. We probably won't have the time and resource to re-write in react by march. Should we aim for September?

**Comment by watsonarw** [comment]
September is a good target I think. Realistically, there aren't a whole lot of different components. The watch view, notifications, state, some smarts around the behaviour of the 5 buttons being different for each page, and a few sample pages. With the exception of the sample pages, these should exist within a framework which we just pull in and use.

Whilst we're at it, at may be worthwhile having a broader discussion around what sort of things we're looking to teach with the LevelUp project, and whether building a watch app is still what we want to use (it could be, but if we're rebuilding, it's worth asking the question).

**Comment by watsonarw** [comment]
We've started working on rewriting this in react, over at https://github.com/twlevelup/watch_edition_react
