### ISSUE TITLE
Move to another CI

### ISSUE THREAD

**Issue by raytung** [twlevelup/watch_edition#36]
SnapCI is shutting down

https://blog.snap-ci.com/blog/2017/02/06/2017-02-06-snap-announcement/

**Comment by raytung** [comment]
I prefer CIs that provide a pipeline / workflow view.

**Comment by katmlee** [comment]
For the current team repos(orange and green), we've migrated them to circle ci. Once we get access to heroku for this repo's deployment we can also migrate it circle ci. Do you have another preference? @raytung

**Comment by raytung** [comment]
@katmlee This repo is already building on Circle. I personally prefer SnapCI's pipeline view where we can see the code pushes from 1 stage to another. AFAIK, WerckerCI is the only hosted CI that has this at the moment http://blog.wercker.com/introducing-wercker-workflows
