### ISSUE TITLE
./go test is *REALLY* slow

### ISSUE THREAD

**Issue by watsonarw** [twlevelup/watch_edition#37]
Running `./go test` takes far too long, and it makes TDD difficult.

On my machine:
```bash
$ time ./go test
...
./go test  37.65s user 1.11s system 105% cpu 36.800 total
```

Breaking it down:

```
$ time npm run stylecheck
...
npm run stylecheck  1.52s user 0.17s system 110% cpu 1.533 total
```
and
```
$ time npm run test
...
npm run test  36.85s user 1.11s system 105% cpu 36.011 total
```

The majority of this time is coming from the test script, and visually, it looks like it's largely the phantomjs/karma boot time. Once it starts, the tests seem to run relatively quickly.

A quick mitigation might be to enable `autoWatch: true` in our karma-conf, and disabling it for CI. It would mean that it boots once, then runs the tests multiple times.

Ultimately, I think we should update from the jasmine/karma/phantomjs testing stack to something like [mocha]/[chai]/[jsdom], which should have a much faster boot time.

*Note: I'm not sure if our test coverage work with the new stack, or if we will need to replace it.*

[mocha]: https://mochajs.org/
[chai]: http://chaijs.com/
[jsdom]: https://github.com/tmpvar/jsdom

**Comment by watsonarw** [comment]
I quickly tried turning on `autoWatch` and turning off `singleRun`, and it's definitely the test startup time. Subsequent runs are much faster. However, there seems to be a problem with some of our tests reloading the page, which makes the suite fail on the subsequent run.

**Comment by raytung** [comment]
webpack.config

`devtool: '#inline-source-map'` 
` ./go test  47.15s user 1.59s system 97% cpu 49.875 total`

`devtool: '#cheap-module-eval-source-map'` 
` ./go test  12.93s user 0.97s system 112% cpu 12.351 total`

**Comment by raytung** [comment]
Removing `webpack.optimize.UglifyJsPlugin` from webpack.config also did the trick
