### ISSUE TITLE
Tests can't be run individually

### ISSUE THREAD

**Issue by watsonarw** [twlevelup/watch_edition#38]
The `eventsList.spec.js` tests will fail if you try to run the without first running the `app.spec.js` tests. The error I'm getting is:
```
TypeError: undefined is not an object (evaluating 'window.App.navigate')
```

I suspect that importing `app.js` at the top of the file will make it work.

**Comment by raytung** [comment]
Hmm I can't reproduce this. I used `fdescribe` on the top level block and the tests ran without a hitch.

**Comment by watsonarw** [comment]
Ah, good call. `fdescribe` and `xdescribe` will probably work because it's still loading in `app.js` which will set up `window.App`. When you run just the `eventsList.spec.js` file, it fails because it doesn't set up `window.App`. The fix is probably something like explicitly setting `window.App` in every suite that needs it, but there are probably quite a few that get it as a side effect of importing `app.js` at any point before the test runs.
