### ISSUE TITLE
Update testing stack from karma/jasmine/phantomjs to mocha/chai/jsdom

### ISSUE THREAD

**Issue by watsonarw** [twlevelup/watch_edition#41]
Our testing stack is old and clunky. It causes a number of random, platform dependant issues, and is slow to start.

Migrating to a more modern testing stack like `mocha`/`chai`/`jsdom` would make running tests faster, and get us away from the gigantic, native binary that is phantomjs, thus reducing the number of platform dependant issues.

**Comment by watsonarw** [comment]
Now that we're using jest, we _should_ be able to kill the phantomjs dependency.

**Comment by honsq90** [comment]
yep removed phantomjs
