### ISSUE TITLE
Replace grunt with npm scripts?

### ISSUE THREAD

**Issue by emirose** [twlevelup/watch_edition#5]
With webpack working, grunt will not be needed for much. Can we simplify things by using npm scripts instead? For example: 
npm run test (to run tests)
npm run start (to run the web dev server)
npm run dist (to build the app)

**Comment by watsonarw** [comment]
I've replaced all the grunt tasks with npm scripts, and removed grunt (and extensions) from the dependencies. There are still a few mentions of grunt in the readme and Wiki, which I need to clean up.
