### ISSUE TITLE
No team page spec for first commit tutorial

### ISSUE THREAD

**Issue by adamhope** [twlevelup/watch_edition#50]
It is not possible to complete the first commit tutorial because there is no spec to add tests to for the team page.

**Comment by honsq90** [comment]
[spec exists here](https://github.com/twlevelup/watch_edition/blob/master/client/spec/pages/teamPage.spec.js)

and [wiki exists here](https://github.com/twlevelup/watch_edition/wiki/Tutorial-2:-Your-first-commit)
