### ISSUE TITLE
Fun project: Create a Chrome extension to replace CCMenu/CCTray

### ISSUE THREAD

**Issue by honsq90** [twlevelup/watch_edition#66]
Just a thought. https://developer.chrome.com/extensions/getstarted

**Comment by watsonarw** [comment]
Something like [BuildReactor](https://chrome.google.com/webstore/detail/buildreactor/agfdekbncfakhgofmaacjfkpbhjhpjmp)

**Comment by honsq90** [comment]
hmm, I'm not a fan of the set up process of BuildReactor. Would be nice to simplify it as:
1. Paste circleci url
2. Done
