### ISSUE TITLE
Remove node-sass

### ISSUE THREAD

**Issue by honsq90** [twlevelup/watch_edition#67]
This is causing issues on Windows machines, and we don't really need scss for the purpose of level up. We should be able to rely plainly on css

**Comment by honsq90** [comment]
or maybe postcss? https://medium.com/@Kirkhammetz/moving-from-sass-to-postcss-why-what-and-how-f68b1bc760dc

**Comment by watsonarw** [comment]
This came up in the discussion when rebuilt this in react. Here's the relevant issue: https://github.com/twlevelup/watch_edition_react/issues/2

**Comment by saranglove** [comment]
So is the decision is to rely on vanilla css?
And one global stylesheet with specific ones for individual pages?

**Comment by honsq90** [comment]
Yep, we won't be doing too much nested stylesheets in each page anyway so vanilla css will do.

There's probably some cleanup in the framework scss files as well, we just need to convert them to vanilla syntax

**Comment by saranglove** [comment]
So the spike #70 is that kinda what you're thinking we should be doing?
