### ISSUE TITLE
.go script for Windows

### ISSUE THREAD

**Issue by honsq90** [twlevelup/watch_edition#68]
could be a powershell script

**Comment by watsonarw** [comment]
I haven't used windows in a while, but what stops the current `./go` script from working in Git bash? If possible, it'd be nice to have things work cross platform with as few platform specific pieces as possible IMO. (It would be nice if Docker for Windows worked in the "home" version that most people have...)

**Comment by honsq90** [comment]
maybe as part of the installation tutorial, we could install something like http://cmder.net/
