### ISSUE TITLE
Simplify folder structure

### ISSUE THREAD

**Issue by honsq90** [twlevelup/watch_edition#69]
It might be easier to structure the folders this way?

- client/src/pages
  - homePage
    - homePage.js
    - homePage.spec.js
    - homePage.css
    - homePage.hbs
  - otherPage
    - otherPage.js
    - otherPage.spec.js
    - otherPage.css
    - otherPage.hbs

**Comment by honsq90** [comment]
Remaining work is to update the wiki to reflect this new folder structure. This can wait until the current Sydney build is over.

**Comment by saranglove** [comment]
Just wondering, will the framework folder structure also need reorganising?
