### ISSUE TITLE
Add double/triple click

### ISSUE THREAD

**Issue by honsq90** [twlevelup/watch_edition#75]
twlevelup/syd-2018-sem1-jupiter@35bb73e

Inspired by this, but exposed in an elegant way in the framework

**Comment by honsq90** [comment]
https://github.com/twlevelup/syd-2018-sem1-jupiter/commit/35bb73eaeecefeac8783f067c942f3f25e51820f

Inspired by this, but exposed in an elegant way in the framework

**Comment by xygoh** [comment]
added double click logic in App.js and implementable methods in BasePage
