### ISSUE TITLE
add docs about how to create a new page 

### ISSUE THREAD

**Issue by emirose** [twlevelup/watch_edition#9]
It might be nice to have some step by step instructions in the wiki about how to create a new page. These instructions should include example tests. Maybe look at Rails Girls tutorials for an example?

**Comment by adamhope** [comment]
https://github.com/twlevelup/watch_edition/wiki/Creating-your-first-page

Reasonably complete guide to creating a new page, not with TDD. I'll do another pass soon where it's all TDD'd.

**Comment by watsonarw** [comment]
I feel like this is now done at: https://github.com/twlevelup/watch_edition/wiki/Tutorial:-Creating-your-first-page

@adamhope are you happy if we close this issue?
